# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base:        2113c51135785ed7f247a4b9685e5f2343121c955ab231add52949231671df43db1ba7f95404b603c7d6b9db7c68803656e1b176c4ad626f688586a8bfcaf524
  asquared_url:           http://localhost:3000
  # you may need to go generate these in asquared: RemoteClient.create!(name: 'portal', secret: 'some secret')
  asquared_api_name:      portal
  asquared_api_secret:    some secret

test:
  secret_key_base: fb35170ec28c907fa52f7db629910c01054c2338ea3ef59ed2e53a1e991d4050a896d426df071f310e59e2a2666ce7d41312720e61689ee4ff1bcbd64f0b0362

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base:     <%= ENV["SECRET_KEY_BASE"] %>
  asquared_url:        <%= ENV["ASQUARED_API_URL"] %>
  asquared_api_name:   <%= ENV["ASQUARED_API_NAME"] %>
  asquared_api_secret: <%= ENV["ASQUARED_API_SECRET"] %>
